/**
 * Карточки Mine — главная экономика игры. Все числа считаются из тира карточки:
 *   цена уровня n:   round(baseCost × costMultiplier^(n−1))
 *   прибыль уровня n: round(baseProfit × profitMultiplier^(n−1)) — прирост прибыли в час за этот уровень
 * Окупаемость первого уровня ≈ 4–10 ч (растёт с тиром), к 9–10 уровню переваливает за 100 ч —
 * проверка: npm run balance-check.
 *
 * Названия и описания вымышленные: никаких реальных брендов и соцсетей.
 * Иконка — "glyph/badge/palette" (см. shared/src/cards.ts).
 */
import type { CardCategory } from '@meowgul/shared';

export type CardCondition =
  | { type: 'card'; cardId: string; level: number }
  | { type: 'friends'; count: number }
  | { type: 'task'; taskId: string }
  | { type: 'league'; level: number };

export interface CardConfig {
  id: string;
  category: CardCategory;
  nameRu: string;
  nameEn: string;
  descRu: string;
  descEn: string;
  icon: string;
  baseCost: number;
  baseProfit: number;
  costMultiplier: number;
  profitMultiplier: number;
  maxLevel: number;
  cooldownSec: number;
  condition: CardCondition | null;
  isLimited: boolean;
  sortOrder: number;
}

type Tier = 1 | 2 | 3 | 4 | 5 | 6;

/** Базовая цена и окупаемость первого уровня (ч) по тирам. */
const TIERS: Record<Tier, { cost: number; payback: number; mult: [number, number, number] }> = {
  1: { cost: 1_000, payback: 4.5, mult: [1.7, 1.75, 1.8] },
  2: { cost: 12_000, payback: 5.5, mult: [1.75, 1.8, 1.85] },
  3: { cost: 150_000, payback: 6.5, mult: [1.8, 1.85, 1.9] },
  4: { cost: 2_000_000, payback: 7.5, mult: [1.85, 1.9, 2.0] },
  5: { cost: 25_000_000, payback: 8.5, mult: [1.9, 2.0, 2.1] },
  6: { cost: 300_000_000, payback: 10, mult: [2.0, 2.1, 2.2] },
};

function twoDigits(n: number): number {
  const p = 10 ** Math.max(0, Math.floor(Math.log10(n)) - 1);
  return Math.round(n / p) * p;
}

/** Канал Telegram из задания «Подписаться на канал» (см. tasks.ts). */
export const CHANNEL_TASK_ID = 'tg_channel';

interface Def {
  id: string;
  tier: Tier;
  /** множитель цены внутри тира */
  k?: number;
  icon: string;
  ru: [string, string];
  en: [string, string];
  cond?: CardCondition;
  /** кулдаун после покупки уровня, сек */
  cd?: number;
  max?: number;
}

const card = (cardId: string, level: number): CardCondition => ({ type: 'card', cardId, level });
const friends = (count: number): CardCondition => ({ type: 'friends', count });
const league = (level: number): CardCondition => ({ type: 'league', level });
const task = (taskId: string): CardCondition => ({ type: 'task', taskId });

const MARKETS: Def[] = [
  {
    id: 'mk_spot',
    tier: 1,
    k: 0.8,
    icon: 'candles/none/0',
    ru: ['Спот-торговля', 'Покупай дёшево, продавай дорого. Кот уже понял схему.'],
    en: ['Spot Trading', 'Buy low, sell high. The cat has already figured it out.'],
  },
  {
    id: 'mk_futures',
    tier: 1,
    k: 1,
    icon: 'chart_line/clock/4',
    ru: ['Фьючерсы', 'Торгуем завтрашним днём, пока все спят.'],
    en: ['Futures', 'Trading tomorrow while everyone is asleep.'],
  },
  {
    id: 'mk_staking',
    tier: 1,
    k: 1.2,
    icon: 'coins/lock/0',
    ru: ['Стейкинг', 'Монеты лежат и размножаются, как котята весной.'],
    en: ['Staking', 'Coins sit still and multiply like kittens in spring.'],
  },
  {
    id: 'mk_p2p',
    tier: 1,
    k: 0.9,
    icon: 'handshake/P2P/3',
    ru: ['P2P-обмен', 'Лапа к лапе, без посредников.'],
    en: ['P2P Exchange', 'Paw to paw, no middlemen.'],
  },
  {
    id: 'mk_margin10',
    tier: 1,
    k: 1.4,
    icon: 'bars/x10/4',
    ru: ['Маржа x10', 'Смелость, умноженная на десять.'],
    en: ['Margin x10', 'Courage times ten.'],
  },
  {
    id: 'mk_memes',
    tier: 1,
    k: 1.1,
    icon: 'rocket/MEME/8',
    ru: ['Мем-токены', 'Курс растёт от каждой смешной фотки кота. Удобно.'],
    en: ['Meme Tokens', 'The price pumps with every funny cat pic. Handy.'],
  },
  {
    id: 'mk_margin20',
    tier: 2,
    k: 0.9,
    icon: 'bars/x20/11',
    ru: ['Маржа x20', 'Для тех, кому x10 показалось скучным.'],
    en: ['Margin x20', 'For those who found x10 boring.'],
    cond: card('mk_margin10', 5),
  },
  {
    id: 'mk_defi',
    tier: 2,
    k: 1,
    icon: 'chip/DeFi/3',
    ru: ['DeFi-токены', 'Финансы без банков, зато с котами.'],
    en: ['DeFi Tokens', 'Finance without banks, but with cats.'],
    cond: card('mk_staking', 3),
  },
  {
    id: 'mk_gamefi',
    tier: 2,
    k: 1.1,
    icon: 'gamepad/coin/2',
    ru: ['GameFi', 'Играй и зарабатывай. Кот так живёт с рождения.'],
    en: ['GameFi', 'Play to earn. The cat has lived like this since birth.'],
    cond: card('mk_memes', 3),
  },
  {
    id: 'mk_options',
    tier: 2,
    k: 1.2,
    icon: 'scales/check/5',
    ru: ['Опционы', 'Право, но не обязанность. Как с миской в шесть утра.'],
    en: ['Options', 'A right, not an obligation. Like the food bowl at 6 am.'],
    cond: card('mk_futures', 4),
  },
  {
    id: 'mk_launchpad',
    tier: 2,
    k: 1.3,
    icon: 'rocket/star/1',
    ru: ['Лаунчпад', 'Новые токены взлетают отсюда. Иногда даже вверх.'],
    en: ['Launchpad', 'New tokens take off from here. Sometimes even upwards.'],
    cond: card('mk_spot', 5),
  },
  {
    id: 'mk_copytrade',
    tier: 2,
    k: 0.8,
    icon: 'people/up/7',
    ru: ['Копитрейдинг', 'Повторяй за успешными котами: мур-мур-профит.'],
    en: ['Copy Trading', 'Copy successful cats: purr-purr-profit.'],
    cond: card('mk_spot', 3),
  },
  {
    id: 'mk_bots',
    tier: 2,
    k: 1.4,
    icon: 'robot/AI/9',
    ru: ['Торговые боты', 'Торгуют круглосуточно и никогда не просят корма.'],
    en: ['Trading Bots', 'Trade around the clock and never ask for food.'],
    cond: card('mk_futures', 3),
  },
  {
    id: 'mk_nft',
    tier: 3,
    k: 0.9,
    icon: 'palette/NFT/6',
    ru: ['NFT-маркет', 'Картинки котов за миллионы. Наконец-то справедливость.'],
    en: ['NFT Market', 'Cat pictures for millions. Justice at last.'],
    cond: card('mk_memes', 6),
  },
  {
    id: 'mk_lending',
    tier: 3,
    k: 1,
    icon: 'bank/coin/0',
    ru: ['Займы под залог', 'Даём в долг под честное кошачье слово. И залог.'],
    en: ['Crypto Lending', 'Loans on a cat’s word of honour. And collateral.'],
    cond: card('mk_defi', 4),
  },
  {
    id: 'mk_index',
    tier: 3,
    k: 1.1,
    icon: 'pie/up/4',
    ru: ['Крипто-индекс', 'Всего понемногу, как в хорошем корме.'],
    en: ['Crypto Index', 'A bit of everything, like good cat food.'],
    cond: card('mk_options', 4),
  },
  {
    id: 'mk_otc',
    tier: 3,
    k: 1.3,
    icon: 'briefcase/VIP/2',
    ru: ['OTC-стол', 'Крупные сделки в тихой комнате с бархатной подушкой.'],
    en: ['OTC Desk', 'Big deals in a quiet room with a velvet cushion.'],
    cond: league(3),
  },
  {
    id: 'mk_swap',
    tier: 3,
    k: 0.8,
    icon: 'bolt/coin/8',
    ru: ['Мгновенный своп', 'Обмен быстрее, чем кот роняет чашку со стола.'],
    en: ['Instant Swap', 'Swaps faster than a cat knocks a cup off the table.'],
    cond: card('mk_p2p', 5),
  },
  {
    id: 'mk_liquidity',
    tier: 3,
    k: 1.2,
    icon: 'drop/plus/3',
    ru: ['Пулы ликвидности', 'Миска с ликвидностью всегда должна быть полной.'],
    en: ['Liquidity Pools', 'The liquidity bowl must always be full.'],
    cond: card('mk_defi', 5),
  },
  {
    id: 'mk_prediction',
    tier: 3,
    k: 1,
    icon: 'crystal_ball/none/9',
    ru: ['Рынок предсказаний', 'Ставки на то, уронит ли кот ёлку в этом году.'],
    en: ['Prediction Market', 'Bets on whether the cat topples the tree this year.'],
    cond: card('mk_options', 5),
  },
  {
    id: 'mk_derivatives',
    tier: 4,
    k: 0.9,
    icon: 'chart_line/PRO/5',
    ru: ['Деривативы', 'Производные от производных. Кот кивает с умным видом.'],
    en: ['Derivatives', 'Derivatives of derivatives. The cat nods wisely.'],
    cond: card('mk_margin20', 5),
    cd: 600,
  },
  {
    id: 'mk_algo_fund',
    tier: 4,
    k: 1.1,
    icon: 'server/up/9',
    ru: ['Алгоритмический фонд', 'Нейросеть торгует, а кот получает дивиденды и почёт.'],
    en: ['Algo Fund', 'The neural net trades, the cat gets dividends and glory.'],
    cond: card('mk_bots', 7),
    cd: 1800,
  },
  {
    id: 'mk_insurance_fund',
    tier: 4,
    k: 1,
    icon: 'shield/coin/7',
    ru: ['Страховой фонд', 'На случай, если рынок упадёт с подоконника.'],
    en: ['Insurance Fund', 'In case the market falls off the windowsill.'],
    cond: friends(3),
    cd: 900,
  },
  {
    id: 'mk_metaverse',
    tier: 4,
    k: 1.3,
    icon: 'globe/sparkle/6',
    ru: ['Мета-биржа', 'Виртуальный офис с бесконечными коробками.'],
    en: ['Meta Exchange', 'A virtual office with endless cardboard boxes.'],
    cond: card('mk_nft', 5),
    cd: 3600,
  },
  {
    id: 'mk_cross_chain',
    tier: 4,
    k: 1.2,
    icon: 'bridge/none/3',
    ru: ['Кросс-чейн мост', 'Монеты ходят между сетями, как кот между комнатами.'],
    en: ['Cross-chain Bridge', 'Coins roam between chains like a cat between rooms.'],
    cond: card('mk_swap', 6),
    cd: 1200,
  },
  {
    id: 'mk_market_maker',
    tier: 5,
    k: 1,
    icon: 'scales/coin/0',
    ru: ['Маркет-мейкинг', 'Держим стакан ровно, как кот держит равновесие на заборе.'],
    en: ['Market Making', 'Keeping the order book steady, like a cat on a fence.'],
    cond: league(5),
    cd: 7200,
  },
  {
    id: 'mk_hedge',
    tier: 5,
    k: 1.2,
    icon: 'cat_head/nine/2',
    ru: ['Хедж-фонд «Девять жизней»', 'Девять жизней — девять стратегий защиты капитала.'],
    en: ['Nine Lives Hedge Fund', 'Nine lives, nine ways to protect capital.'],
    cond: card('mk_insurance_fund', 5),
    cd: 14400,
  },
  {
    id: 'mk_tokenization',
    tier: 5,
    k: 1.1,
    icon: 'building/coin/5',
    ru: ['Токенизация недвижимости', 'Продаём квартиры по кусочку. Подоконник — отдельный лот.'],
    en: ['Real Estate Tokens', 'Selling flats piece by piece. The windowsill is a separate lot.'],
    cond: card('mk_metaverse', 5),
    cd: 10800,
  },
  {
    id: 'mk_own_chain',
    tier: 6,
    k: 1,
    icon: 'chain/crown/9',
    ru: ['Свой блокчейн', 'Блоки подтверждаются мурлыканьем. Энергоэффективно.'],
    en: ['Own Blockchain', 'Blocks are confirmed by purring. Very energy efficient.'],
    cond: league(7),
    cd: 43200,
  },
  {
    id: 'mk_global_exchange',
    tier: 6,
    k: 1.3,
    icon: 'skyscraper/globe/0',
    ru: ['Мировая биржа Meowgul', 'Небоскрёб с лапкой на крыше. Видно из космоса.'],
    en: ['Meowgul World Exchange', 'A skyscraper with a paw on the roof. Visible from space.'],
    cond: card('mk_own_chain', 3),
    cd: 86400,
  },
];

const PR_TEAM: Def[] = [
  {
    id: 'pr_support',
    tier: 1,
    k: 0.8,
    icon: 'headset/247/1',
    ru: ['Служба поддержки', 'Мурлычем клиентам круглосуточно.'],
    en: ['Support Team', 'Purring to customers around the clock.'],
  },
  {
    id: 'pr_blog',
    tier: 1,
    k: 0.9,
    icon: 'book/pen/6',
    ru: ['Блог компании', 'Пишем посты лапой. Медленно, но с душой.'],
    en: ['Company Blog', 'Posts written with a paw. Slowly, but with soul.'],
  },
  {
    id: 'pr_memes',
    tier: 1,
    k: 1,
    icon: 'smiley/fire/8',
    ru: ['Мем-отдел', 'Лучшие мемы про котов — наши. Остальные тоже.'],
    en: ['Meme Department', 'The best cat memes are ours. The rest too.'],
  },
  {
    id: 'pr_mascot',
    tier: 1,
    k: 1.2,
    icon: 'mascot/star/2',
    ru: ['Ростовая кукла кота', 'Человек в костюме кота. Настоящий кот не впечатлён.'],
    en: ['Cat Mascot Suit', 'A human in a cat suit. The real cat is not impressed.'],
  },
  {
    id: 'pr_hr',
    tier: 1,
    k: 1.1,
    icon: 'people/plus/1',
    ru: ['Отдел кадров', 'Нанимаем котов с опытом лежания от трёх лет.'],
    en: ['HR Department', 'Hiring cats with 3+ years of napping experience.'],
  },
  {
    id: 'pr_designer',
    tier: 1,
    k: 1.3,
    icon: 'palette/pen/6',
    ru: ['Дизайнер', 'Делает логотип больше, а лапку — пожирнее.'],
    en: ['Designer', 'Makes the logo bigger and the paw bolder.'],
  },
  {
    id: 'pr_media',
    tier: 2,
    k: 0.9,
    icon: 'newspaper/LIVE/11',
    ru: ['Своё медиа', 'Главная новость дня: кот проснулся.'],
    en: ['Own Media', 'Breaking news: the cat woke up.'],
    cond: card('pr_blog', 3),
  },
  {
    id: 'pr_video',
    tier: 2,
    k: 1.1,
    icon: 'video/play/1',
    ru: ['Свой видеоканал', 'Ролик «Кот смотрит в стену» набрал миллион.'],
    en: ['Own Video Channel', '“Cat stares at the wall” hit a million views.'],
    cond: card('pr_media', 3),
  },
  {
    id: 'pr_partners',
    tier: 2,
    k: 1,
    icon: 'handshake/heart/6',
    ru: ['Партнёрская программа', 'Приведи друга — получи вкусняшку.'],
    en: ['Partner Program', 'Bring a friend, get a treat.'],
    cond: card('pr_hr', 4),
  },
  {
    id: 'pr_community',
    tier: 2,
    k: 0.8,
    icon: 'chat/heart/7',
    ru: ['Комьюнити-менеджер', 'Отвечает в чате быстрее, чем кот прибегает на звук пакета.'],
    en: ['Community Manager', 'Replies faster than a cat runs to a rustling bag.'],
    cond: card('pr_support', 4),
  },
  {
    id: 'pr_podcast',
    tier: 2,
    k: 1.2,
    icon: 'mic/music/9',
    ru: ['Подкаст «Мур-новости»', 'Час мурчания о рынках. Слушатели засыпают счастливыми.'],
    en: ['Purr News Podcast', 'An hour of purring about markets. Listeners fall asleep happy.'],
    cond: card('pr_blog', 4),
  },
  {
    id: 'pr_seo',
    tier: 2,
    k: 1.3,
    icon: 'magnifier/SEO/3',
    ru: ['SEO-котик', 'По запросу «лучший кот» — мы на первом месте.'],
    en: ['SEO Kitty', 'Search “best cat” — we are number one.'],
    cond: card('pr_blog', 5),
  },
  {
    id: 'pr_events',
    tier: 2,
    k: 1.4,
    icon: 'ticket/star/8',
    ru: ['Ивент-агентство', 'Вечеринки, после которых все коробки заняты.'],
    en: ['Event Agency', 'Parties after which every box is occupied.'],
    cond: card('pr_mascot', 3),
  },
  {
    id: 'pr_influencers',
    tier: 3,
    k: 1,
    icon: 'camera/heart/6',
    ru: ['Котоблогеры', 'Миллион подписчиков и ни одного поста без лапки в кадре.'],
    en: ['Cat Influencers', 'A million followers and not one post without a paw.'],
    cond: card('pr_video', 4),
  },
  {
    id: 'pr_tv',
    tier: 3,
    k: 1.2,
    icon: 'tv/TV/1',
    ru: ['Реклама на ТВ', 'Тридцать секунд кота в прайм-тайм.'],
    en: ['TV Commercials', 'Thirty seconds of cat in prime time.'],
    cond: league(3),
  },
  {
    id: 'pr_billboards',
    tier: 3,
    k: 0.9,
    icon: 'billboard/none/8',
    ru: ['Билборды', 'Огромный кот смотрит на водителей с осуждением.'],
    en: ['Billboards', 'A giant cat judges every driver on the highway.'],
    cond: card('pr_designer', 5),
  },
  {
    id: 'pr_cto',
    tier: 3,
    k: 1.3,
    icon: 'laptop/crown/9',
    ru: ['Технический директор', 'Знает, где горячий ноутбук, и спит на нём.'],
    en: ['CTO', 'Knows where the warm laptop is and sleeps on it.'],
    cond: card('pr_hr', 6),
  },
  {
    id: 'pr_analytics',
    tier: 3,
    k: 1.1,
    icon: 'calculator/up/5',
    ru: ['Отдел аналитики', 'Посчитали: 87% времени кот спит. Остальное — тоже.'],
    en: ['Analytics Team', 'Fact: the cat sleeps 87% of the time. The rest too.'],
    cond: card('pr_seo', 4),
  },
  {
    id: 'pr_translators',
    tier: 3,
    k: 0.8,
    icon: 'globe/chat/3',
    ru: ['Переводчики', 'Переводим «мяу» на 40 языков без потери смысла.'],
    en: ['Translators', 'Translating “meow” into 40 languages, no meaning lost.'],
    cond: card('pr_community', 5),
  },
  {
    id: 'pr_ambassadors',
    tier: 3,
    k: 1,
    icon: 'medal/people/0',
    ru: ['Амбассадоры', 'Лучшие друзья компании в каждом дворе.'],
    en: ['Ambassadors', 'Best friends of the company in every backyard.'],
    cond: friends(2),
  },
  {
    id: 'pr_conference',
    tier: 4,
    k: 1,
    icon: 'stage/star/2',
    ru: ['Конференция «Мяу-Саммит»', 'Главный доклад: «Почему коробка лучше кровати».'],
    en: ['Meow Summit', 'Keynote: “Why a box beats a bed”.'],
    cond: card('pr_events', 6),
    cd: 900,
  },
  {
    id: 'pr_charity',
    tier: 4,
    k: 0.9,
    icon: 'heart/paw/11',
    ru: ['Фонд помощи бездомным котам', 'Каждая сделка кормит кота из приюта. Мур спасибо.'],
    en: ['Shelter Cat Fund', 'Every trade feeds a shelter cat. Purr-thanks.'],
    cond: task(CHANNEL_TASK_ID),
    cd: 600,
  },
  {
    id: 'pr_esports',
    tier: 4,
    k: 1.2,
    icon: 'gamepad/trophy/9',
    ru: ['Киберспортивная команда', 'Реакция как у кота на лазерную указку.'],
    en: ['Esports Team', 'Reflexes like a cat chasing a laser dot.'],
    cond: card('pr_influencers', 5),
    cd: 1800,
  },
  {
    id: 'pr_movie',
    tier: 4,
    k: 1.3,
    icon: 'clapper/star/1',
    ru: ['Фильм о компании', 'Драма в трёх частях: голод, миска, счастье.'],
    en: ['Company Movie', 'A drama in three acts: hunger, bowl, happiness.'],
    cond: card('pr_tv', 5),
    cd: 3600,
  },
  {
    id: 'pr_ai_assistant',
    tier: 4,
    k: 1.1,
    icon: 'robot/chat/7',
    ru: ['ИИ-ассистент «Мурчик»', 'Отвечает на любой вопрос. Чаще всего — «мяу».'],
    en: ['AI Assistant Purry', 'Answers any question. Usually with “meow”.'],
    cond: card('pr_cto', 5),
    cd: 1200,
  },
  {
    id: 'pr_world_tour',
    tier: 5,
    k: 1,
    icon: 'plane/globe/5',
    ru: ['Мировое турне', 'Двадцать стран, двадцать новых коробок.'],
    en: ['World Tour', 'Twenty countries, twenty new boxes.'],
    cond: friends(10),
    cd: 7200,
  },
  {
    id: 'pr_stadium',
    tier: 5,
    k: 1.2,
    icon: 'stadium/none/4',
    ru: ['Название стадиона', 'Стадион «Meowgul Арена». Газон регулярно проверяется котом.'],
    en: ['Stadium Naming', 'Meowgul Arena. The lawn is inspected by the cat daily.'],
    cond: league(6),
    cd: 14400,
  },
  {
    id: 'pr_space_ad',
    tier: 5,
    k: 1.1,
    icon: 'satellite/star/9',
    ru: ['Реклама на орбите', 'Лапку видно даже с Луны.'],
    en: ['Ad in Orbit', 'The paw is visible even from the Moon.'],
    cond: card('pr_movie', 5),
    cd: 10800,
  },
  {
    id: 'pr_academy',
    tier: 6,
    k: 1,
    icon: 'graduation/crown/2',
    ru: ['Академия Meowgul', 'Учим котят трейдингу. Выпускники ловят тренды и мышей.'],
    en: ['Meowgul Academy', 'Teaching kittens to trade. Graduates catch trends and mice.'],
    cond: league(7),
    cd: 43200,
  },
  {
    id: 'pr_holiday',
    tier: 6,
    k: 1.3,
    icon: 'calendar/heart/6',
    ru: ['Международный день кота', 'Теперь это официальный праздник. Благодаря нам.'],
    en: ['International Cat Day', 'It’s an official holiday now. Thanks to us.'],
    cond: card('pr_academy', 3),
    cd: 86400,
  },
];

const LEGAL: Def[] = [
  {
    id: 'lg_kyc',
    tier: 1,
    k: 0.8,
    icon: 'id_card/KYC/5',
    ru: ['KYC', 'Проверяем, что ты не собака.'],
    en: ['KYC', 'Making sure you are not a dog.'],
  },
  {
    id: 'lg_aml',
    tier: 1,
    k: 0.9,
    icon: 'shield/AML/9',
    ru: ['AML-отдел', 'Ловим грязные деньги, как мышей.'],
    en: ['AML Department', 'Catching dirty money like mice.'],
  },
  {
    id: 'lg_opinion',
    tier: 1,
    k: 1,
    icon: 'document/check/10',
    ru: ['Юридическое заключение', 'Двенадцать страниц, чтобы сказать «можно».'],
    en: ['Legal Opinion', 'Twelve pages to say “yes, you can”.'],
  },
  {
    id: 'lg_compliance',
    tier: 1,
    k: 1.2,
    icon: 'police_badge/none/5',
    ru: ['Комплаенс-офицер', 'Строгий, но справедливый. Как кот у миски.'],
    en: ['Compliance Officer', 'Strict but fair. Like a cat at the food bowl.'],
  },
  {
    id: 'lg_terms',
    tier: 1,
    k: 1.1,
    icon: 'scroll/pen/10',
    ru: ['Пользовательское соглашение', 'Никто не читал, но все согласились.'],
    en: ['Terms of Service', 'Nobody read it, everybody agreed.'],
  },
  {
    id: 'lg_trademark',
    tier: 1,
    k: 1.3,
    icon: 'stamp/TM/9',
    ru: ['Товарный знак', 'Лапка на монете — только наша.'],
    en: ['Trademark', 'The paw on the coin is ours alone.'],
  },
  {
    id: 'lg_license_eu',
    tier: 2,
    k: 1,
    icon: 'document/EU/5',
    ru: ['Лицензия Европа', 'Европейские коты одобряют. Особенно французские.'],
    en: ['License: Europe', 'European cats approve. Especially the French ones.'],
    cond: card('lg_compliance', 3),
  },
  {
    id: 'lg_license_asia',
    tier: 2,
    k: 1.1,
    icon: 'document/AS/11',
    ru: ['Лицензия Азия', 'Манэки-нэко машет лапой в знак согласия.'],
    en: ['License: Asia', 'The lucky cat waves its paw in approval.'],
    cond: card('lg_compliance', 4),
  },
  {
    id: 'lg_license_na',
    tier: 2,
    k: 1.2,
    icon: 'document/NA/3',
    ru: ['Лицензия Сев. Америка', 'Шесть месяцев бумаг и одна печать с лапкой.'],
    en: ['License: North America', 'Six months of paperwork and one paw-print stamp.'],
    cond: card('lg_license_eu', 3),
  },
  {
    id: 'lg_license_africa',
    tier: 2,
    k: 1.1,
    icon: 'document/AF/8',
    ru: ['Лицензия Африка', 'Большие кошки саванны уважают нашу лапку.'],
    en: ['License: Africa', 'The big cats of the savanna respect our paw.'],
    cond: card('lg_license_asia', 3),
  },
  {
    id: 'lg_tax',
    tier: 2,
    k: 0.9,
    icon: 'percent/coin/4',
    ru: ['Налоговый консультант', 'Всё легально. Даже вкусняшки проведены по статье «мотивация».'],
    en: ['Tax Advisor', 'All legal. Even treats are booked as “motivation”.'],
    cond: card('lg_opinion', 4),
  },
  {
    id: 'lg_audit',
    tier: 2,
    k: 1.3,
    icon: 'code/check/7',
    ru: ['Аудит смарт-контрактов', 'Нашли баг. Это был кот на клавиатуре.'],
    en: ['Smart Contract Audit', 'Found a bug. It was the cat on the keyboard.'],
    cond: card('lg_kyc', 4),
  },
  {
    id: 'lg_gdpr',
    tier: 2,
    k: 1.4,
    icon: 'lock/key/10',
    ru: ['Защита данных', 'Ваши данные надёжнее, чем вкусняшки на верхней полке.'],
    en: ['Data Protection', 'Your data is safer than treats on the top shelf.'],
    cond: card('lg_aml', 4),
  },
  {
    id: 'lg_license_latam',
    tier: 3,
    k: 1,
    icon: 'document/LA/1',
    ru: ['Лицензия Лат. Америка', 'Подписано под звуки самбы и мурлыканья.'],
    en: ['License: Latin America', 'Signed to the sound of samba and purring.'],
    cond: card('lg_license_na', 3),
  },
  {
    id: 'lg_license_oceania',
    tier: 3,
    k: 1.1,
    icon: 'document/OC/7',
    ru: ['Лицензия Океания', 'Даже кенгуру не возражают.'],
    en: ['License: Oceania', 'Even the kangaroos have no objections.'],
    cond: card('lg_license_asia', 5),
  },
  {
    id: 'lg_lawyers',
    tier: 3,
    k: 1.2,
    icon: 'gavel/none/10',
    ru: ['Бюро «Когти и партнёры»', 'Цепкие юристы. В прямом смысле.'],
    en: ['Claws & Partners', 'Lawyers with a firm grip. Literally.'],
    cond: card('lg_opinion', 5),
  },
  {
    id: 'lg_proof_reserves',
    tier: 3,
    k: 1.3,
    icon: 'vault/check/0',
    ru: ['Подтверждение резервов', 'Пересчитали все монеты. Кот следил, чтобы ни одна не укатилась.'],
    en: ['Proof of Reserves', 'Counted every coin. The cat made sure none rolled away.'],
    cond: card('lg_audit', 4),
  },
  {
    id: 'lg_cold_storage',
    tier: 3,
    k: 0.9,
    icon: 'wallet/snow/3',
    ru: ['Холодный кошелёк', 'Хранится в холодильнике, рядом с рыбой. Двойная охрана.'],
    en: ['Cold Storage', 'Kept in the fridge next to the fish. Double security.'],
    cond: card('lg_gdpr', 4),
  },
  {
    id: 'lg_bug_bounty',
    tier: 3,
    k: 1,
    icon: 'bug/coin/4',
    ru: ['Охота на баги', 'Платим за найденных жуков. Кот уже принёс трёх.'],
    en: ['Bug Hunt', 'We pay for every bug found. The cat brought three already.'],
    cond: card('lg_audit', 3),
  },
  {
    id: 'lg_sandbox',
    tier: 3,
    k: 0.8,
    icon: 'box/check/8',
    ru: ['Регуляторная песочница', 'Регулятор разрешил играть в песочнице. Кот доволен.'],
    en: ['Regulatory Sandbox', 'The regulator allowed us to play in the sandbox. The cat is pleased.'],
    cond: league(2),
  },
  {
    id: 'lg_central_bank',
    tier: 4,
    k: 1,
    icon: 'bank/chat/5',
    ru: ['Диалог с центробанком', 'Обсудили ставку. Кот настаивал на рыбной.'],
    en: ['Central Bank Talks', 'Discussed the rate. The cat insisted on a fish rate.'],
    cond: league(4),
    cd: 1800,
  },
  {
    id: 'lg_insurance',
    tier: 4,
    k: 1.1,
    icon: 'umbrella/coin/3',
    ru: ['Страховка депозитов', 'Если что — у нас есть зонтик. И девять жизней.'],
    en: ['Deposit Insurance', 'Just in case, we have an umbrella. And nine lives.'],
    cond: card('lg_proof_reserves', 5),
    cd: 900,
  },
  {
    id: 'lg_arbitration',
    tier: 4,
    k: 1.2,
    icon: 'scales/globe/10',
    ru: ['Международный арбитраж', 'Спор о подоконнике разрешён в нашу пользу.'],
    en: ['International Arbitration', 'The windowsill dispute was settled in our favour.'],
    cond: card('lg_lawyers', 5),
    cd: 3600,
  },
  {
    id: 'lg_lobby',
    tier: 4,
    k: 1,
    icon: 'briefcase/star/11',
    ru: ['Лоббист в парламенте', 'Продвигает закон о бесплатной рыбе по пятницам.'],
    en: ['Lobbyist', 'Pushing a law for free fish on Fridays.'],
    cond: friends(5),
    cd: 1800,
  },
  {
    id: 'lg_security',
    tier: 4,
    k: 1.3,
    icon: 'shield/eye/9',
    ru: ['Служба безопасности', 'Не спит никогда. Ну, почти никогда.'],
    en: ['Security Team', 'Never sleeps. Well, almost never.'],
    cond: card('lg_cold_storage', 5),
    cd: 1200,
  },
  {
    id: 'lg_banking',
    tier: 5,
    k: 1.1,
    icon: 'bank/crown/0',
    ru: ['Банковская лицензия', 'Теперь мы банк. Сейф обит мягким пледом.'],
    en: ['Banking License', 'We are a bank now. The vault is lined with a soft blanket.'],
    cond: card('lg_central_bank', 5),
    cd: 14400,
  },
  {
    id: 'lg_global_compliance',
    tier: 5,
    k: 1,
    icon: 'globe/check/5',
    ru: ['Глобальный комплаенс', 'Соответствуем правилам во всех странах и на всех подоконниках.'],
    en: ['Global Compliance', 'Compliant in every country and on every windowsill.'],
    cond: card('lg_license_latam', 5),
    cd: 7200,
  },
  {
    id: 'lg_court',
    tier: 5,
    k: 1.2,
    icon: 'gavel/trophy/2',
    ru: ['Победа в верховном суде', 'Суд признал: коробка принадлежит коту.'],
    en: ['Supreme Court Win', 'The court ruled: the box belongs to the cat.'],
    cond: card('lg_arbitration', 5),
    cd: 10800,
  },
  {
    id: 'lg_own_jurisdiction',
    tier: 6,
    k: 1,
    icon: 'flag/paw/9',
    ru: ['Своя юрисдикция «Котландия»', 'Флаг с лапкой, гимн — мурлыканье.'],
    en: ['Catland Jurisdiction', 'A flag with a paw, purring as the anthem.'],
    cond: league(7),
    cd: 43200,
  },
  {
    id: 'lg_crypto_council',
    tier: 6,
    k: 1.3,
    icon: 'crown/globe/0',
    ru: ['Место в мировом крипто-совете', 'Кот голосует лапой. Всегда — за рыбу.'],
    en: ['World Crypto Council Seat', 'The cat votes with a paw. Always for fish.'],
    cond: card('lg_own_jurisdiction', 3),
    cd: 86400,
  },
];

const SPECIALS: Def[] = [
  {
    id: 'sp_ceo_photo',
    tier: 1,
    k: 1.5,
    icon: 'character/star/0',
    ru: ['Фотосессия CEO', 'Кот на обложке журнала. Тираж раскупили за минуту.'],
    en: ['CEO Photoshoot', 'The cat on a magazine cover. Sold out in a minute.'],
  },
  {
    id: 'sp_cardboard_hq',
    tier: 1,
    k: 1.2,
    icon: 'box/heart/8',
    ru: ['Офис в коробке', 'Самый любимый офис любого кота. Аренда бесплатная.'],
    en: ['Cardboard Box HQ', 'Every cat’s favourite office. Rent-free.'],
  },
  {
    id: 'sp_laser',
    tier: 2,
    k: 0.8,
    icon: 'laser/none/11',
    ru: ['Лазерная указка', 'Мотивация отдела продаж выросла на 300%.'],
    en: ['Laser Pointer', 'Sales team motivation is up 300%.'],
    cond: friends(1),
  },
  {
    id: 'sp_yarn',
    tier: 2,
    k: 1,
    icon: 'yarn/none/6',
    ru: ['Клубок ниток', 'Тимбилдинг: распутываем вместе.'],
    en: ['Ball of Yarn', 'Team building: untangling together.'],
    cond: task(CHANNEL_TASK_ID),
  },
  {
    id: 'sp_fish_fund',
    tier: 2,
    k: 1.2,
    icon: 'fish/coin/3',
    ru: ['Рыбный фонд', 'Инвестируем в тунец. Самый стабильный актив.'],
    en: ['Fish Fund', 'Investing in tuna. The most stable asset.'],
    cond: card('mk_staking', 5),
  },
  {
    id: 'sp_catnip',
    tier: 2,
    k: 1.1,
    icon: 'leaf/sparkle/4',
    ru: ['Лаунж с кошачьей мятой', 'Креативность отдела маркетинга зашкаливает.'],
    en: ['Catnip Lounge', 'The marketing team’s creativity is off the charts.'],
    cond: friends(3),
  },
  {
    id: 'sp_nap_room',
    tier: 2,
    k: 1.3,
    icon: 'moon/zzz/9',
    ru: ['Комната для сна', 'Производительность растёт во сне. Проверено.'],
    en: ['Nap Room', 'Productivity grows while you sleep. Proven.'],
    cond: league(2),
  },
  {
    id: 'sp_scratching_post',
    tier: 3,
    k: 0.9,
    icon: 'post/crown/0',
    ru: ['Золотая когтеточка', 'Точить когти о золото — признак успеха.'],
    en: ['Golden Scratching Post', 'Sharpening claws on gold is a sign of success.'],
    cond: card('pr_designer', 5),
  },
  {
    id: 'sp_aquarium',
    tier: 3,
    k: 1,
    icon: 'aquarium/bubble/3',
    ru: ['Аквариум в переговорке', 'Переговоры идут быстрее, когда все смотрят на рыбок.'],
    en: ['Meeting Room Aquarium', 'Meetings go faster when everyone watches the fish.'],
    cond: card('lg_compliance', 5),
  },
  {
    id: 'sp_window_seat',
    tier: 3,
    k: 1.1,
    icon: 'window/sun/8',
    ru: ['Место у окна', 'Лучший вид на рынок и на птичек.'],
    en: ['Window Seat', 'The best view of the market. And the birds.'],
    cond: friends(5),
  },
  {
    id: 'sp_tuna_contract',
    tier: 3,
    k: 1.2,
    icon: 'can/check/5',
    ru: ['Контракт на поставку тунца', 'Пожизненный. С индексацией.'],
    en: ['Tuna Supply Contract', 'Lifetime. Inflation-adjusted.'],
    cond: card('lg_opinion', 6),
  },
  {
    id: 'sp_mouse_toy',
    tier: 3,
    k: 0.8,
    icon: 'mouse/key/10',
    ru: ['Заводная мышь', 'Главный тренажёр отдела охоты за трендами.'],
    en: ['Wind-up Mouse', 'The trend-hunting team’s favourite training gear.'],
    cond: card('mk_bots', 4),
  },
  {
    id: 'sp_cat_cafe',
    tier: 3,
    k: 1.3,
    icon: 'cup/paw/8',
    ru: ['Котокафе', 'Кофе бесплатно, коты — бесценно.'],
    en: ['Cat Café', 'Coffee is free, cats are priceless.'],
    cond: league(3),
  },
  {
    id: 'sp_vet',
    tier: 3,
    k: 1,
    icon: 'medkit/plus/11',
    ru: ['Корпоративный ветеринар', 'Полис ДМС: девять жизней застрахованы.'],
    en: ['Corporate Vet', 'Health insurance covers all nine lives.'],
    cond: card('pr_hr', 7),
  },
  {
    id: 'sp_bell_collar',
    tier: 3,
    k: 1.1,
    icon: 'bell/none/0',
    ru: ['Ошейник с бубенчиком', 'Звенит при каждой успешной сделке.'],
    en: ['Bell Collar', 'Rings with every successful trade.'],
    cond: card('mk_spot', 7),
  },
  {
    id: 'sp_milk_bar',
    tier: 4,
    k: 0.9,
    icon: 'milk/none/5',
    ru: ['Молочный бар', 'Безлактозное, для взрослых котов.'],
    en: ['Milk Bar', 'Lactose-free, for grown-up cats.'],
    cond: card('sp_cat_cafe', 3),
    cd: 900,
  },
  {
    id: 'sp_sunbeam',
    tier: 4,
    k: 1,
    icon: 'sun/star/0',
    ru: ['Солнечный луч', 'Арендовали весь солнечный луч в офисе. Навсегда.'],
    en: ['Sunbeam', 'Leased the entire office sunbeam. Forever.'],
    cond: card('sp_window_seat', 3),
    cd: 1200,
  },
  {
    id: 'sp_night_shift',
    tier: 4,
    k: 1.1,
    icon: 'moon/clock/9',
    ru: ['Ночная смена', 'В три часа ночи коты особенно активны. Используем это.'],
    en: ['Night Shift', 'Cats are most active at 3 am. We use that.'],
    cond: card('sp_nap_room', 5),
    cd: 1800,
  },
  {
    id: 'sp_purr_engine',
    tier: 4,
    k: 1.2,
    icon: 'gear/bolt/10',
    ru: ['Мур-двигатель', 'Вечный двигатель на мурлыканье. Физики в шоке.'],
    en: ['Purr Engine', 'A perpetual motion machine powered by purring. Physicists are shocked.'],
    cond: card('pr_cto', 5),
    cd: 3600,
  },
  {
    id: 'sp_lucky_cat',
    tier: 4,
    k: 1.3,
    icon: 'lucky_cat/coin/11',
    ru: ['Манэки-нэко', 'Машет лапой — и монеты приходят сами.'],
    en: ['Lucky Cat', 'It waves its paw and coins just roll in.'],
    cond: friends(7),
    cd: 2400,
  },
  {
    id: 'sp_moon_mission',
    tier: 5,
    k: 1,
    icon: 'rocket/moon/9',
    ru: ['Полёт на Луну', 'Курс — to the moon. Кот уже в скафандре.'],
    en: ['Moon Mission', 'Course set: to the moon. The cat is already suited up.'],
    cond: card('mk_launchpad', 8),
    cd: 7200,
  },
  {
    id: 'sp_time_machine',
    tier: 5,
    k: 1.1,
    icon: 'clock/spiral/2',
    ru: ['Машина времени', 'Слетали в прошлое и купили крипту дёшево.'],
    en: ['Time Machine', 'Went back in time and bought crypto cheap.'],
    cond: league(5),
    cd: 10800,
  },
  {
    id: 'sp_treasure',
    tier: 5,
    k: 1.2,
    icon: 'chest/sparkle/0',
    ru: ['Пиратский клад', 'Карту нарисовал кот. Крестик — это лапка.'],
    en: ['Pirate Treasure', 'The cat drew the map. X marks the paw.'],
    cond: card('sp_lucky_cat', 3),
    cd: 14400,
  },
  {
    id: 'sp_dragon',
    tier: 5,
    k: 1.3,
    icon: 'dragon/fire/11',
    ru: ['Котодракон', 'Охраняет резервы и греет офис зимой.'],
    en: ['Cat Dragon', 'Guards the reserves and heats the office in winter.'],
    cond: card('lg_security', 5),
    cd: 21600,
  },
  {
    id: 'sp_crystal_bowl',
    tier: 5,
    k: 1,
    icon: 'bowl/diamond/3',
    ru: ['Хрустальная миска', 'Из неё даже обычный корм вкуснее.'],
    en: ['Crystal Bowl', 'Even regular food tastes better from it.'],
    cond: friends(10),
    cd: 7200,
  },
  {
    id: 'sp_nine_lives',
    tier: 5,
    k: 1.2,
    icon: 'heart/nine/6',
    ru: ['Девять жизней', 'Компания пережила восемь кризисов. В запасе ещё одна.'],
    en: ['Nine Lives', 'The company survived eight crises. One life to spare.'],
    cond: card('mk_hedge', 3),
    cd: 18000,
  },
  {
    id: 'sp_black_cat_day',
    tier: 5,
    k: 1.1,
    icon: 'calendar/star/9',
    ru: ['День чёрного кота', 'Чёрный кот приносит удачу. Проверено на графиках.'],
    en: ['Black Cat Day', 'Black cats bring luck. Proven on the charts.'],
    cond: league(6),
    cd: 14400,
  },
  {
    id: 'sp_whiskers',
    tier: 6,
    k: 1,
    icon: 'whiskers/crown/0',
    ru: ['Золотые усы', 'Чувствуют движение рынка за неделю.'],
    en: ['Golden Whiskers', 'Sense market moves a week in advance.'],
    cond: card('sp_crystal_bowl', 5),
    cd: 43200,
  },
  {
    id: 'sp_box_fort',
    tier: 6,
    k: 1.2,
    icon: 'castle/none/8',
    ru: ['Крепость из коробок', 'Штаб-квартира мечты. Неприступна для пылесоса.'],
    en: ['Box Fortress', 'The dream HQ. Impregnable to the vacuum cleaner.'],
    cond: league(8),
    cd: 64800,
  },
  {
    id: 'sp_cat_tower',
    tier: 6,
    k: 1.4,
    icon: 'skyscraper/paw/2',
    ru: ['Котоскрёб', 'Небоскрёб с когтеточкой на каждом этаже. Вершина карьеры.'],
    en: ['Cat Tower', 'A skyscraper with a scratching post on every floor. The career peak.'],
    cond: card('sp_box_fort', 3),
    cd: 86400,
  },
];

/** Лимитированные карточки: доступны только в окне availableFrom–availableUntil (расписание — в админке). */
const LIMITED: Def[] = [
  {
    id: 'lt_pumpkin',
    tier: 2,
    k: 1,
    icon: 'pumpkin/moon/8',
    ru: ['Тыквенный кот', 'Страшно выгодно. Только в сезон тыкв.'],
    en: ['Pumpkin Cat', 'Scary profitable. Pumpkin season only.'],
  },
  {
    id: 'lt_newyear_tree',
    tier: 2,
    k: 1.2,
    icon: 'tree/star/4',
    ru: ['Ёлка-когтеточка', 'Наконец-то ёлку можно ронять официально.'],
    en: ['Scratching Tree', 'Finally, toppling the tree is official.'],
  },
  {
    id: 'lt_valentine',
    tier: 2,
    k: 0.9,
    icon: 'envelope/heart/6',
    ru: ['Валентинка с лапкой', 'Признание в любви к инвесторам.'],
    en: ['Paw Valentine', 'A love letter to our investors.'],
  },
  {
    id: 'lt_spring_parade',
    tier: 2,
    k: 1.1,
    icon: 'flower/sun/7',
    ru: ['Весенний котопарад', 'Март. Все коты на улице. Маркетинг сам идёт в руки.'],
    en: ['Spring Cat Parade', 'March. Every cat is outside. Marketing writes itself.'],
  },
  {
    id: 'lt_beach_office',
    tier: 3,
    k: 0.9,
    icon: 'umbrella/sun/3',
    ru: ['Пляжный офис', 'Работаем из-под зонтика. Песок — та же коробка, только большая.'],
    en: ['Beach Office', 'Working under an umbrella. Sand is just a big litter box.'],
  },
  {
    id: 'lt_snow_cat',
    tier: 3,
    k: 1,
    icon: 'snowflake/none/5',
    ru: ['Снежный кот', 'Лепили всем офисом. Растаял на прибыль.'],
    en: ['Snow Cat', 'Built by the whole office. Melted into profit.'],
  },
  {
    id: 'lt_halving',
    tier: 3,
    k: 1.2,
    icon: 'cake/x2/6',
    ru: ['Халвинг-вечеринка', 'Награда делится пополам, торт — нет.'],
    en: ['Halving Party', 'The reward gets halved, the cake does not.'],
  },
  {
    id: 'lt_bull_run',
    tier: 3,
    k: 1.3,
    icon: 'bull/fire/4',
    ru: ['Бычий забег', 'Быки бегут вверх, кот бежит за ними.'],
    en: ['Bull Run', 'The bulls run up, the cat runs after them.'],
  },
  {
    id: 'lt_birthday',
    tier: 3,
    k: 1,
    icon: 'gift/star/1',
    ru: ['День рождения Meowgul', 'Вместо свечей — лазерные указки.'],
    en: ['Meowgul Birthday', 'Laser pointers instead of candles.'],
  },
  {
    id: 'lt_mooncake',
    tier: 3,
    k: 1.1,
    icon: 'mooncake/moon/0',
    ru: ['Праздник лунного пряника', 'Пряник с лапкой. Есть его жалко, инвестировать — нет.'],
    en: ['Mooncake Festival', 'A mooncake with a paw. Too pretty to eat, perfect to invest.'],
  },
  {
    id: 'lt_carnival',
    tier: 4,
    k: 0.9,
    icon: 'mask/sparkle/2',
    ru: ['Карнавал масок', 'Никто не знает, кто под маской. Но хвост выдаёт.'],
    en: ['Mask Carnival', 'Nobody knows who’s behind the mask. The tail gives it away.'],
  },
  {
    id: 'lt_fireworks',
    tier: 4,
    k: 1,
    icon: 'fireworks/none/9',
    ru: ['Фейерверк в офисе', 'Красиво! Кот, правда, теперь живёт под диваном.'],
    en: ['Office Fireworks', 'Beautiful! The cat lives under the sofa now, though.'],
  },
  {
    id: 'lt_cat_olympics',
    tier: 4,
    k: 1.1,
    icon: 'torch/star/8',
    ru: ['Котолимпиада', 'Прыжки на шкаф, бег за лазером, синхронное умывание.'],
    en: ['Cat Olympics', 'Wardrobe high jump, laser sprint, synchronized grooming.'],
  },
  {
    id: 'lt_black_friday',
    tier: 4,
    k: 1.2,
    icon: 'bag/percent/11',
    ru: ['Чёрная пятница', 'Скидки на корм. Кот скупил всё.'],
    en: ['Black Friday', 'Cat food on sale. The cat bought everything.'],
  },
  {
    id: 'lt_million_cats',
    tier: 5,
    k: 1,
    icon: 'trophy/crown/0',
    ru: ['Миллион котов', 'Нас уже миллион. Мурлычем хором!'],
    en: ['A Million Cats', 'We are a million strong. Purring in chorus!'],
  },
];

/** Цена уровня не превышает MAX_LEVEL_PRICE — числа остаются точными целыми и читаемыми. */
export const MAX_LEVEL_PRICE = 1e15;

function cappedMaxLevel(baseCost: number, costMultiplier: number, wanted: number): number {
  let level = wanted;
  while (level > 1 && baseCost * costMultiplier ** (level - 1) > MAX_LEVEL_PRICE) level--;
  return level;
}

function build(category: CardCategory, defs: Def[], limited = false): CardConfig[] {
  return defs.map((d, i) => {
    const tier = TIERS[d.tier];
    const baseCost = twoDigits(tier.cost * (d.k ?? 1));
    // небольшой разброс окупаемости внутри тира: 0.9–1.15
    const payback = tier.payback * (0.9 + ((i * 7) % 6) * 0.05);
    const costMultiplier = tier.mult[i % 3]!;
    const profitMultiplier = Math.min(1.2, Math.max(1.05, Math.round((costMultiplier / 1.48) * 100) / 100));
    return {
      id: d.id,
      category,
      nameRu: d.ru[0],
      nameEn: d.en[0],
      descRu: d.ru[1],
      descEn: d.en[1],
      icon: d.icon,
      baseCost,
      baseProfit: Math.max(1, Math.round(baseCost / payback)),
      costMultiplier,
      profitMultiplier,
      maxLevel: cappedMaxLevel(
        baseCost,
        costMultiplier,
        d.max ?? (limited ? 10 : category === 'SPECIALS' ? 20 : 25),
      ),
      cooldownSec: d.cd ?? 0,
      condition: d.cond ?? null,
      isLimited: limited,
      sortOrder: i,
    };
  });
}

export const CARDS: readonly CardConfig[] = [
  ...build('MARKETS', MARKETS),
  ...build('PR_TEAM', PR_TEAM),
  ...build('LEGAL', LEGAL),
  ...build('SPECIALS', SPECIALS),
  ...build('SPECIALS', LIMITED, true).map((c, i) => ({ ...c, sortOrder: 100 + i })),
];

export const LIMITED_CARD_IDS: readonly string[] = LIMITED.map((d) => d.id);

/**
 * Автоматическая ротация лимитированных карточек, для которых админ не задал окно вручную:
 * всегда в продаже `concurrent` карточек, каждая по `slotHours` часов, по кругу в порядке sortOrder.
 * Отсчёт — от epoch (день в UTC, час — время ежедневного сброса).
 */
export const LIMITED_ROTATION = { epoch: '2026-01-01', slotHours: 72, concurrent: 2 } as const;

/** Цена покупки уровня level (1 — первая покупка). */
export function cardLevelCost(c: Pick<CardConfig, 'baseCost' | 'costMultiplier'>, level: number): number {
  return Math.round(c.baseCost * c.costMultiplier ** (level - 1));
}

/** Прирост прибыли в час, который даёт уровень level. */
export function cardLevelProfit(
  c: Pick<CardConfig, 'baseProfit' | 'profitMultiplier'>,
  level: number,
): number {
  return Math.round(c.baseProfit * c.profitMultiplier ** (level - 1));
}

/** Суммарная прибыль карточки в час на уровне level. */
export function cardTotalProfit(
  c: Pick<CardConfig, 'baseProfit' | 'profitMultiplier'>,
  level: number,
): number {
  let sum = 0;
  for (let n = 1; n <= level; n++) sum += cardLevelProfit(c, n);
  return sum;
}
